### ISSUE TITLE
Windows, how to use environment variable?

### ISSUE THREAD

**Issue by ninovanhooff** [pd-rs/get-playdate-sdk#29]
This action fails while the env var seems to be set allright. Is that because the env var is only set in git bash and I'm not using that?

https://github.com/ninovanhooff/LibHEBitmap/actions/runs/8930413593/job/24530460948

Relevant CmakeLists.txt error:
https://github.com/ninovanhooff/LibHEBitmap/blob/3df3c67818640d6004d43bd098fe2ed96ccc6552/CMakeLists.txt#L20

My workflow:
https://github.com/ninovanhooff/LibHEBitmap/actions/runs/8930413593/workflow

**Comment by boozook** [comment]
Hi @ninovanhooff 👋
We're [using bash everywhere](https://github.com/boozook/playdate/blob/main/.github/workflows/tests.yml#L45-L47).
There is [real usage example](https://github.com/boozook/playdate/blob/main/.github/workflows/tests.yml#L83-L92).

You're right, env var `PLAYDATE_SDK_PATH` is set from bash but should be set not only for bash.
If you want it in another shel such as powershell or cmd, you can get the path of SDK from action' outputs, like this:

```yaml
- id: sdk
  uses: # this action
...
# You can use ${{ steps.sdk.outputs.root }} or ${{ env.PLAYDATE_SDK_PATH }}.
# This is for pwsh:
- run: echo "PLAYDATE_SDK_PATH=${{ steps.sdk.outputs.root }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
  shell: pwsh
```

Or for your case, I could try to add [there](https://github.com/ninovanhooff/LibHEBitmap/actions/runs/8930413593/workflow#L48-L50)  and [there](https://github.com/ninovanhooff/LibHEBitmap/actions/runs/8930413593/workflow#L58-L60) env var via GitHub's api:
```yaml
- name: Configure CMake
  env: # this 👇
    PLAYDATE_SDK_PATH: ${{ steps.sdk.outputs.root }}
  # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
  # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
  run: >
    cmake -B ${{ steps.strings.outputs.build-output-dir }}
    ...
```
I didn't tested this way, but supposed to work according to [GH's docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable).

Anyway, that's strange, IMHO, because I writing env in normal way that recommended by GH ([1][], [2][], [3][]).

[1]: https://github.com/pd-rs/get-playdate-sdk/blob/main/action.yml#L105
[2]: https://github.com/pd-rs/get-playdate-sdk/blob/main/action.yml#L116
[3]: https://github.com/pd-rs/get-playdate-sdk/blob/main/action.yml#L137

- - -

That is strange, I see that env already set in your workflow.
See this [linux](https://github.com/ninovanhooff/LibHEBitmap/actions/runs/8930413593/job/24530460717#step:5:5) [win](https://github.com/ninovanhooff/LibHEBitmap/actions/runs/8930413593/job/24530460948#step:5:5) lines.

<img width="662" alt="Screenshot 2024-05-05 at 02 43 57" src="https://github.com/pd-rs/get-playdate-sdk/assets/888526/30351a7a-e170-49b3-ae10-77763bdff513">

And on linux CMake wants you to set env var `CMAKE_MAKE_PROGRAM` [there](https://github.com/ninovanhooff/LibHEBitmap/actions/runs/8930413593/job/24530460717#step:5:7).
